server:
  port: 8080
  servlet:
    context-path: /demo


spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/springboottest"
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true